baseurl = "/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  contentTypeName = "notes"
  showMenuItems = 9
  fullWidthTheme = false
  centerTheme = false
  showLastUpdated = true
  updatedDatePrefix = "Updated:"
  dateFormat = "2006-01-02"

[[assets.fuseOpts]]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
  keys = ["title", "permalink", "summary", "content"]

[languages]
  [languages.en]
    languageName = "English"
    title = "n3s0 || journal"
    copyright = "© 2025 Timothy Loftus (n3s0)"

    [languages.en.params]
      subtitle = "Where I put my thoughts, ideas, and project updates."
      owner = "Timothy Loftus (n3s0)"
      keywords = "journal notes networking tech"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other Posts"
      newerPosts = "Newer"
      olderPosts = "Older"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

    [languages.en.params.logo]
      logoText = "n3s0 || journal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "journal"
        name = "Journal"
        url = "/journal"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes"
        weight = 11
      [[languages.en.menu.main]]
        identifier = "build"
        name = "Build"
        url = "/build"
        weight = 30
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 31
      [[languages.en.menu.main]]
        identifier = "bookmarks"
        name = "Bookmarks"
        url = "/bookmarks"
        weight = 40
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/construction"
        weight = 41
      [[languages.en.menu.main]]
        identifier = "support"
        name = "Support"
        url = "/support"
        weight = 42
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/n3s0"
        weight = 43
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
        weight = 44
      [[languages.en.menu.main]]
        identifier = "computer"
        name = "Computer"
        url = "/construction"
        weight = 60
      [[languages.en.menu.main]]
        identifier = "infrastructure"
        name = "Infrastructure"
        url = "/construction"
        weight = 61
      [[languages.en.menu.main]]
        identifier = "edc"
        name = "EDC"
        url = "/construction"
        weight = 62
      [[languages.en.menu.main]]
        identifier = "library"
        name = "Library"
        url = "/construction"
        weight = 63
      [[languages.en.menu.main]]
        identifier = "travel"
        name = "Travel"
        url = "/construction"
        weight = 68
